version: '3.8'
services:
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USERNAME: sensor_user_rabbit
      RABBIT_PASSWORD: sensor_password_rabbit
    links:
      - rabbitmq
    networks:
      - data-stream-network

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    environment:
      SENSOR_IDS: '1,2,3,4,5,6'
      RABBIT_HOST: rabbitmq
      RABBIT_USERNAME: sensor_user_rabbit
      RABBIT_PASSWORD: sensor_password_rabbit
    links:
      - rabbitmq
    networks:
      - data-stream-network


  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      RABBITMQ_USERNAME: sensor_user_rabbit
      RABBITMQ_PASSWORD: sensor_password_rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
    networks:
      - data-stream-network

networks:
  data-stream-network:
    driver: 'bridge'

volumes:
  rabbitmq_data:
    driver: local